import type {
  ActivityRecord,
  EsDraft,
  GakuchikaRecord,
  ProfileSummary,
} from "@/types/domain";

export const PROFILE: ProfileSummary = {
  name: "山田 太郎",
  school: "Gakuchika University",
  faculty: "経営学部",
  grade: "3年",
  target: "IT・SaaS業界",
};

export const MOCK_ACTIVITIES: ActivityRecord[] = [
  {
    id: "activity-001",
    title: "学園祭の企画班で導線改善を担当",
    body: "来場者の動きと混雑箇所を整理し、案内表示と導線を見直した。写真付きで改善前後を比較できるように記録した。",
    categoryKey: "club",
    tagIds: ["leadership", "teamwork", "improvement"],
    date: "2026-07-26",
    photoAsset: require("../../assets/images/tutorial-web.png"),
    photoLabel: "改善前後の導線メモ",
    metrics: ["来場者満足度 +18%", "案内ミス -32%"],
    location: "大学祭実行委員会",
    createdAt: "2026-07-26T09:00:00.000Z",
    updatedAt: "2026-07-26T09:00:00.000Z",
  },
  {
    id: "activity-007",
    title: "商社インターンで営業資料の改善提案を実施",
    body: "提案資料の見せ方を整理し、相手の理解が進みやすい構成に改善した。",
    categoryKey: "internship",
    tagIds: ["presentation", "analysis", "improvement"],
    date: "2026-07-10",
    photoAsset: require("../../assets/images/react-logo.png"),
    photoLabel: "営業提案の構成メモ",
    metrics: ["資料の理解時間 -20%", "質問件数 -3件"],
    location: "商社インターン",
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "activity-008",
    title: "AIイベントでプロトタイプを発表した",
    body: "学生向けの体験型コンテンツを題材に、プロトタイプと改善ポイントを発表した。",
    categoryKey: "competition",
    tagIds: ["presentation", "innovation", "teamwork"],
    date: "2026-07-08",
    photoAsset: require("../../assets/images/logo-glow.png"),
    photoLabel: "発表時のデモ画面",
    metrics: ["入賞 1位", "デモ完走 100%"],
    location: "学内ハッカソン",
    createdAt: "2026-07-08T09:30:00.000Z",
    updatedAt: "2026-07-08T09:30:00.000Z",
  },
  {
    id: "activity-002",
    title: "React学習会でUI改善を発表",
    body: "アクセシビリティを意識したコンポーネント分割を紹介し、画面設計の意図を説明した。",
    categoryKey: "development",
    tagIds: ["react", "uiux", "presentation"],
    date: "2026-07-24",
    photoAsset: require("../../assets/images/react-logo.png"),
    photoLabel: "勉強会スライド",
    metrics: ["発表 15分", "質問 6件"],
    location: "開発サークル",
    createdAt: "2026-07-24T10:00:00.000Z",
    updatedAt: "2026-07-24T10:00:00.000Z",
  },
  {
    id: "activity-003",
    title: "ゼミで競合分析の資料を作成",
    body: "数字の根拠を揃えて、比較の観点を整理。説明の順番まで意識して資料を作成した。",
    categoryKey: "research",
    tagIds: ["analysis", "numbers", "presentation"],
    date: "2026-07-20",
    metrics: ["比較対象 8社", "資料 12ページ"],
    location: "マーケティングゼミ",
    createdAt: "2026-07-20T12:00:00.000Z",
    updatedAt: "2026-07-20T12:00:00.000Z",
  },
  {
    id: "activity-004",
    title: "アルバイトで新人教育マニュアルを刷新",
    body: "手順の抜け漏れを洗い出し、写真と短い説明で読みやすい資料にまとめた。",
    categoryKey: "part-time",
    tagIds: ["teamwork", "improvement", "numbers"],
    date: "2026-07-18",
    photoAsset: require("../../assets/images/expo-logo.png"),
    photoLabel: "手順書の改善メモ",
    metrics: ["教育時間 -25%", "質問回数 -40%"],
    location: "カフェ",
    createdAt: "2026-07-18T15:00:00.000Z",
    updatedAt: "2026-07-18T15:00:00.000Z",
  },
  {
    id: "activity-005",
    title: "就活イベントで自己分析を深めた",
    body: "強みの再整理を行い、面接で話す材料を活動ベースで棚卸しした。",
    categoryKey: "study",
    tagIds: ["recruiting", "analysis"],
    date: "2026-07-15",
    metrics: ["面談 2回", "メモ 18件"],
    location: "キャリアセンター",
    createdAt: "2026-07-15T08:00:00.000Z",
    updatedAt: "2026-07-15T08:00:00.000Z",
  },
  {
    id: "activity-006",
    title: "ボランティアで配布物の導線を整備",
    body: "参加者が迷わないように案内の流れを見直し、現場で試しながら修正した。",
    categoryKey: "volunteer",
    tagIds: ["teamwork", "leadership"],
    date: "2026-07-11",
    photoAsset: require("../../assets/images/logo-glow.png"),
    photoLabel: "案内フローの図",
    metrics: ["案内時間 -10分", "参加者 60名"],
    location: "地域イベント",
    createdAt: "2026-07-11T11:00:00.000Z",
    updatedAt: "2026-07-11T11:00:00.000Z",
  },
];

export const CATEGORY_COUNT_MAP = MOCK_ACTIVITIES.reduce(
  (acc, activity) => {
    acc[activity.categoryKey] = (acc[activity.categoryKey] ?? 0) + 1;
    return acc;
  },
  {} as Record<string, number>,
);

export const MOCK_GAKUCHIKA: GakuchikaRecord[] = [
  {
    id: "gk-001",
    title: "学園祭の導線改善",
    overview: "混雑しやすい導線を整理し、案内と役割分担を見直した経験。",
    period: "2026年6月 - 2026年7月",
    role: "企画班リーダー",
    challenge: "来場者が分散せず、受付前に行列ができていた。",
    difficulty: "前例がなく、当日の現場判断が多かった。",
    action: "導線図を作成し、案内担当と誘導担当を分けた。",
    result: "案内の停滞を減らし、運営全体の待ち時間を短縮した。",
    learning: "現場では情報を1枚にまとめると動きやすい。",
    numbers: ["来場者満足度 +18%", "案内ミス -32%"],
    artifact: "導線図 / 写真 / 当日の運営メモ",
    relatedActivityIds: ["activity-001", "activity-006"],
    createdAt: "2026-07-26T09:00:00.000Z",
    updatedAt: "2026-07-26T09:00:00.000Z",
  },
  {
    id: "gk-002",
    title: "React学習会の発表",
    overview: "UI改善の考え方を整理し、学習会で発表した経験。",
    period: "2026年7月",
    role: "発表者",
    challenge: "自分の知識を短時間で伝える必要があった。",
    difficulty: "聞き手の理解レベルに差があった。",
    action: "画面のBefore/Afterを使って、設計意図から説明した。",
    result: "質疑で実装の考え方まで話せるようになった。",
    learning: "概念だけでなく具体画面を並べると伝わりやすい。",
    numbers: ["発表 15分", "質問 6件"],
    artifact: "スライド / GitHub / 画面キャプチャ",
    relatedActivityIds: ["activity-002"],
    createdAt: "2026-07-24T10:00:00.000Z",
    updatedAt: "2026-07-24T10:00:00.000Z",
  },
  {
    id: "gk-003",
    title: "アルバイトの教育改善",
    overview: "新人教育の抜け漏れを減らすために手順書を更新した経験。",
    period: "2026年7月",
    role: "教育担当",
    challenge: "教える人によって説明の内容がばらついていた。",
    difficulty: "忙しい時間帯でも読める資料が必要だった。",
    action: "写真付きのマニュアルと、確認用の短いチェックリストを作った。",
    result: "教育時間を短縮し、質問の回数も減った。",
    learning: "現場改善は、相手の負担を下げる設計が大事。",
    numbers: ["教育時間 -25%", "質問回数 -40%"],
    artifact: "手順書 / 写真 / チェックリスト",
    relatedActivityIds: ["activity-004"],
    createdAt: "2026-07-18T15:00:00.000Z",
    updatedAt: "2026-07-18T15:00:00.000Z",
  },
];

export const MOCK_ES_DRAFTS: EsDraft[] = [
  {
    id: "es-001",
    title: "学園祭の経験を使ったガクチカ",
    prompt: "大学生活で最も力を入れたことを400字でまとめる",
    content:
      "学園祭で混雑導線を見直し、案内担当と誘導担当を分けて待ち時間を削減した。...",
    wordCount: 164,
    relatedGakuchikaId: "gk-001",
    relatedActivityIds: ["activity-001", "activity-006"],
    updatedAt: "2026-07-26T09:20:00.000Z",
  },
  {
    id: "es-002",
    title: "アルバイトでの改善経験",
    prompt: "課題に対して工夫したことを整理する",
    content:
      "教育時間を短縮するために、写真付きマニュアルとチェックリストを整えた。...",
    wordCount: 132,
    relatedGakuchikaId: "gk-003",
    relatedActivityIds: ["activity-004"],
    updatedAt: "2026-07-18T15:30:00.000Z",
  },
];
