/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/es/index` | `/es/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gakuchika/index` | `/gakuchika/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activities` | `/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/es` | `/es`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gakuchika` | `/gakuchika`; params?: Router.UnknownInputParams; } | { pathname: `/activities/new`; params?: Router.UnknownInputParams; } | { pathname: `/albums`; params?: Router.UnknownInputParams; } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/es`; params?: Router.UnknownInputParams; } | { pathname: `/gakuchika`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/activities/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gakuchika/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/es/index` | `/es/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gakuchika/index` | `/gakuchika/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/activities` | `/activities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/es` | `/es`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gakuchika` | `/gakuchika`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/new`; params?: Router.UnknownOutputParams; } | { pathname: `/albums`; params?: Router.UnknownOutputParams; } | { pathname: `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/es`; params?: Router.UnknownOutputParams; } | { pathname: `/gakuchika`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/activities/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/gakuchika/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/es/index${`?${string}` | `#${string}` | ''}` | `/es/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gakuchika/index${`?${string}` | `#${string}` | ''}` | `/gakuchika/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/activities${`?${string}` | `#${string}` | ''}` | `/activities${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/es${`?${string}` | `#${string}` | ''}` | `/es${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gakuchika${`?${string}` | `#${string}` | ''}` | `/gakuchika${`?${string}` | `#${string}` | ''}` | `/activities/new${`?${string}` | `#${string}` | ''}` | `/albums${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `/es${`?${string}` | `#${string}` | ''}` | `/gakuchika${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/es/index` | `/es/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gakuchika/index` | `/gakuchika/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activities` | `/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/es` | `/es`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gakuchika` | `/gakuchika`; params?: Router.UnknownInputParams; } | { pathname: `/activities/new`; params?: Router.UnknownInputParams; } | { pathname: `/albums`; params?: Router.UnknownInputParams; } | { pathname: `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/es`; params?: Router.UnknownInputParams; } | { pathname: `/gakuchika`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | `/activities/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/gakuchika/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/activities/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/gakuchika/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
